-- Run after schema.sql. Only lore and characters; no demo accounts, actors or ideas.
begin;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('a7b414fa-b6e9-5916-a989-6132fff46c7c', 'Жора', 'Обычный новокузнецкий парень, попавший не в то место и не в то время. Вынужден бороться с Доном криминальными методами.', 'Характер уточним по полному разбору.', 'Борется с Доном криминальными методами.', 'Противник Дона Потника. Карпуха — член банды Жоры.', 'Сведения из прежнего разбора. Конфликт связан с пропавшей партией кокаина и долгом в миллион долларов.', 'uncertain', 1) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('c4017715-0437-529c-a99a-6aa571d12ab1', 'Дон Потник', 'Унаследовал преступную империю. Его конфликт с Жорой — одна из центральных линий.', 'Характер уточним по полному разбору.', 'Стоит во главе собственной группировки.', 'Противостоит Жоре. Туз — его правая рука. Фёдор и Дима Черен — члены его банды.', 'В прежнем разборе отмечены похищения, убийства и перестрелка в ходе конфликта.', 'uncertain', 2) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('81b67d78-39e8-584e-a891-6b018eea6309', 'Туз', 'Правая рука Дона Потника.', 'Подробное описание пока не перенесено.', 'Близкий участник команды Дона.', 'Связан с Доном Потником.', 'Данные из доступного контекста прежнего разбора.', 'uncertain', 4) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('a211dbea-b7db-5c72-9857-7955e17a8a31', 'Святослав', 'Его роль связана с пленением и подозрением в предательстве.', 'Не определён в доступном кратком разборе.', 'Его роль и связь с информатором остаются нераскрытыми.', 'Связи нужно уточнить по полному разбору.', 'Пленение Святослава — одна из отмеченных линий. Не делаем вывод о предательстве без подтверждения.', 'uncertain', 5) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('e40cbe4a-1c29-5f73-a46c-ab50d9f62a3b', 'Паша', 'В прежнем разборе отмечена его гибель.', 'Подробности нужно дополнить.', 'Возвращение в финальном фильме требует сюжетного решения.', 'Подробности нужно дополнить.', 'Гибель отмечена в доступном контексте. Обстоятельства уточним по полному разбору.', 'uncertain', 6) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('833ee109-060c-5764-a8ec-3fc57e510c48', 'Ваня', 'В прежнем разборе характеризуется как надёжный участник.', 'Надёжность — отмеченная черта; остальное нужно уточнить.', 'Подробности нужно дополнить.', 'Подробности нужно дополнить.', 'Данные из доступного контекста прежнего разбора.', 'uncertain', 7) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('fb2a036f-ea7a-52c8-a90c-087fd1df1131', 'Химик', 'Персонаж, связанный с наркотиками.', 'Подробности нужно дополнить.', 'Связь с наркотиками отмечена в прежнем разборе.', 'Подробности нужно дополнить.', 'Роль в финальном фильме пока не определена.', 'uncertain', 8) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('5a918ad2-11c9-58c3-87c5-beb50ece6cb4', 'Джорданио Быхулиос', 'Загадочный персонаж.', 'В доступном контексте нет подробностей.', 'Связан с отдельной группировкой.', 'Серёга Авиаторы — его правая рука. Неясно, на чьей стороне Джорданио.', 'Внезапно появляется в конце второй серии. Возможно, играет в свою игру.', 'uncertain', 3) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('ff495b56-f27e-5f2c-b9cc-ac6f6314d0a1', 'Фёдор', 'Член банды Дона Потника.', 'Характер пока не описан.', '', 'Член банды Дона Потника.', 'Роль исполняет организатор проекта.', 'cast', 9) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('fa35935e-3d34-5463-b921-30c5bf7c01d2', 'Карпуха', 'Член банды Жоры.', 'Характер пока не описан.', '', 'Член банды Жоры.', '', 'uncertain', 10) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('39065eb6-6d4e-5cf4-8765-0db6590246e3', 'Дима Черен', 'Член банды Дона Потника.', 'Характер пока не описан.', '', 'Член банды Дона Потника.', '', 'uncertain', 11) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.characters (id, name, description, personality, traits, relationships, history, casting_status, sort_order) values ('b4f6edf8-c6d0-52d5-9d63-04571f098fd2', 'Серёга Авиаторы', 'Правая рука Джорданио Быхулиоса.', 'Характер пока не описан.', '', 'Правая рука Джорданио Быхулиоса.', '', 'uncertain', 12) on conflict (id) do update set name=excluded.name, description=excluded.description, personality=excluded.personality, traits=excluded.traits, relationships=excluded.relationships, history=excluded.history, casting_status=excluded.casting_status, sort_order=excluded.sort_order;
insert into public.lore_chapters (id, title, sort_order, content) values ('ba316eab-8388-5ca5-9852-7d181d091be8', 'Основной конфликт', 1, 'Жора и Дон Потник противостоят друг другу из-за пропавшей партии кокаина и долга в миллион долларов.

В конфликте отмечены похищения, убийства и перестрелка.') on conflict (id) do update set title=excluded.title, sort_order=excluded.sort_order, content=excluded.content;
insert into public.lore_chapters (id, title, sort_order, content) values ('06af110a-37b7-51d4-8910-f1ab5ca5d399', 'Герои и группировки', 2, 'Дон Потник унаследовал преступную империю. Жора, обычный новокузнецкий парень, попавший не в то место и не в то время, вынужден бороться с Доном криминальными методами.

В конце второй серии внезапно появляется загадочный персонаж Джорданио Быхулиос.') on conflict (id) do update set title=excluded.title, sort_order=excluded.sort_order, content=excluded.content;
insert into public.lore_chapters (id, title, sort_order, content) values ('8544d70b-4f54-5845-80fa-26e4d1a28358', 'Что осталось открытым', 3, 'Непонятно, на чьей стороне Джорданио — или он вовсе играет в свою игру.') on conflict (id) do update set title=excluded.title, sort_order=excluded.sort_order, content=excluded.content;
commit;
